[2024-04-28T02:34:36.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T02:34:36.399+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream-dag.get-object manual__2024-04-28T02:34:35.273074+00:00 [queued]>
[2024-04-28T02:34:36.405+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream-dag.get-object manual__2024-04-28T02:34:35.273074+00:00 [queued]>
[2024-04-28T02:34:36.405+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T02:34:36.415+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get-object> on 2024-04-28 02:34:35.273074+00:00
[2024-04-28T02:34:36.423+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6598) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T02:34:36.424+0000] {standard_task_runner.py:63} INFO - Started process 6607 to run task
[2024-04-28T02:34:36.424+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stream-dag', 'get-object', 'manual__2024-04-28T02:34:35.273074+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/new-dag.py', '--cfg-path', '/tmp/tmplyho6fk3']
[2024-04-28T02:34:36.425+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask get-object
[2024-04-28T02:34:36.460+0000] {task_command.py:426} INFO - Running <TaskInstance: stream-dag.get-object manual__2024-04-28T02:34:35.273074+00:00 [running]> on host 2589f30e9678
[2024-04-28T02:34:36.531+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stream-dag' AIRFLOW_CTX_TASK_ID='get-object' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T02:34:35.273074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T02:34:35.273074+00:00'
[2024-04-28T02:34:36.532+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T02:34:37.232+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T02:34:37.233+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/new-dag.py", line 40, in get_object_task
    data = json.loads(obj_data.decode("utf-8"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-04-28T02:34:37.242+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=stream-dag, task_id=get-object, execution_date=20240428T023435, start_date=20240428T023436, end_date=20240428T023437
[2024-04-28T02:34:37.253+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task get-object (Expecting value: line 1 column 1 (char 0); 6607)
[2024-04-28T02:34:37.280+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T02:34:37.291+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T02:34:37.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
