[2024-04-27T00:31:49.655+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T00:31:49.670+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream-dag.count-file manual__2024-04-27T00:31:47.410675+00:00 [queued]>
[2024-04-27T00:31:49.676+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream-dag.count-file manual__2024-04-27T00:31:47.410675+00:00 [queued]>
[2024-04-27T00:31:49.676+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-27T00:31:49.687+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): count-file> on 2024-04-27 00:31:47.410675+00:00
[2024-04-27T00:31:49.697+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2470) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T00:31:49.698+0000] {standard_task_runner.py:63} INFO - Started process 2472 to run task
[2024-04-27T00:31:49.698+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stream-dag', 'count-file', 'manual__2024-04-27T00:31:47.410675+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/new-dag.py', '--cfg-path', '/tmp/tmp6mvwd2pj']
[2024-04-27T00:31:49.700+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask count-file
[2024-04-27T00:31:49.736+0000] {task_command.py:426} INFO - Running <TaskInstance: stream-dag.count-file manual__2024-04-27T00:31:47.410675+00:00 [running]> on host 701d3b82b873
[2024-04-27T00:31:49.810+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stream-dag' AIRFLOW_CTX_TASK_ID='count-file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T00:31:47.410675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T00:31:47.410675+00:00'
[2024-04-27T00:31:49.812+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T00:31:50.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T00:31:50.250+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 262, in fs
    return self._fs_cached
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 436, in __getattr__
    raise AttributeError(item)
AttributeError: _fs_cached. Did you mean: '_hash_cached'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/fs/s3.py", line 50, in get_fs
    from s3fs import S3FileSystem
ModuleNotFoundError: No module named 's3fs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/new-dag.py", line 39, in countfile
    files = [f for f in base.iterdir() if f.is_file()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/implementations/cloud.py", line 51, in iterdir
    if self.is_file():
       ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 717, in is_file
    return self.fs.isfile(self.path)
           ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/upath/core.py", line 264, in fs
    fs = self._fs_cached = self._fs_factory(
                           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/io/path.py", line 77, in _fs_factory
    return attach(protocol or "file", storage_options.get("conn_id")).fs
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/io/store/__init__.py", line 61, in fs
    return get_fs(self.protocol, self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/io/__init__.py", line 109, in get_fs
    return fs(conn_id, options)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/fs/s3.py", line 52, in get_fs
    raise ImportError(
ImportError: Airflow FS S3 protocol requires the s3fs library, but it is not installed as it requiresaiobotocore. Please install the s3 protocol support library by running: pip install apache-airflow-providers-amazon[s3fs]
[2024-04-27T00:31:50.264+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=stream-dag, task_id=count-file, execution_date=20240427T003147, start_date=20240427T003149, end_date=20240427T003150
[2024-04-27T00:31:50.274+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task count-file (Airflow FS S3 protocol requires the s3fs library, but it is not installed as it requiresaiobotocore. Please install the s3 protocol support library by running: pip install apache-airflow-providers-amazon[s3fs]; 2472)
[2024-04-27T00:31:50.313+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T00:31:50.324+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T00:31:50.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
