[2024-04-28T02:18:13.632+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T02:18:13.647+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stream-dag.get-object manual__2024-04-28T02:18:11.485996+00:00 [queued]>
[2024-04-28T02:18:13.652+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stream-dag.get-object manual__2024-04-28T02:18:11.485996+00:00 [queued]>
[2024-04-28T02:18:13.652+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T02:18:13.661+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get-object> on 2024-04-28 02:18:11.485996+00:00
[2024-04-28T02:18:13.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stream-dag', 'get-object', 'manual__2024-04-28T02:18:11.485996+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/new-dag.py', '--cfg-path', '/tmp/tmppzgp1nki']
[2024-04-28T02:18:13.672+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6372) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-28T02:18:13.682+0000] {standard_task_runner.py:63} INFO - Started process 6374 to run task
[2024-04-28T02:18:13.682+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask get-object
[2024-04-28T02:18:13.740+0000] {task_command.py:426} INFO - Running <TaskInstance: stream-dag.get-object manual__2024-04-28T02:18:11.485996+00:00 [running]> on host 2589f30e9678
[2024-04-28T02:18:13.852+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stream-dag' AIRFLOW_CTX_TASK_ID='get-object' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T02:18:11.485996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T02:18:11.485996+00:00'
[2024-04-28T02:18:13.853+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T02:18:14.941+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T02:18:14.943+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/new-dag.py", line 38, in get_object_task
    data = json.loads(obj_data.decode("utf-8"))
           ^^^^
NameError: name 'json' is not defined. Did you forget to import 'json'
[2024-04-28T02:18:14.954+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=stream-dag, task_id=get-object, execution_date=20240428T021811, start_date=20240428T021813, end_date=20240428T021814
[2024-04-28T02:18:14.968+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task get-object (name 'json' is not defined; 6374)
[2024-04-28T02:18:14.981+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T02:18:14.993+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T02:18:14.995+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
