[2024-05-01T00:38:48.893+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T00:38:48.907+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_analysis_dag.test_query manual__2024-05-01T00:38:47.839334+00:00 [queued]>
[2024-05-01T00:38:48.912+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_analysis_dag.test_query manual__2024-05-01T00:38:47.839334+00:00 [queued]>
[2024-05-01T00:38:48.912+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T00:38:48.920+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): test_query> on 2024-05-01 00:38:47.839334+00:00
[2024-05-01T00:38:48.926+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=572) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T00:38:48.927+0000] {standard_task_runner.py:63} INFO - Started process 574 to run task
[2024-05-01T00:38:48.927+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'batch_analysis_dag', 'test_query', 'manual__2024-05-01T00:38:47.839334+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/ml-dag.py', '--cfg-path', '/tmp/tmpqb307q3r']
[2024-05-01T00:38:48.929+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask test_query
[2024-05-01T00:38:48.959+0000] {task_command.py:426} INFO - Running <TaskInstance: batch_analysis_dag.test_query manual__2024-05-01T00:38:47.839334+00:00 [running]> on host 0a71bd2d4f31
[2024-05-01T00:38:49.014+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_analysis_dag' AIRFLOW_CTX_TASK_ID='test_query' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:38:47.839334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T00:38:47.839334+00:00'
[2024-05-01T00:38:49.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T00:38:49.020+0000] {base.py:84} INFO - Using connection ID 'test-mongo-con' for task execution.
[2024-05-01T00:38:49.028+0000] {logger.py:96} INFO - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 66318f193acad48e9783b1bc, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "66318f193acad48e9783b1bc"}, "remainingTimeMS": 29}
[2024-05-01T00:39:19.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T00:39:19.464+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml-dag.py", line 17, in test_query
    result = hook.find(
             ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 233, in find
    return collection.find_one(query, projection, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/collection.py", line 1495, in find_one
    for result in cursor.limit(-1):
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 1243, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 1160, in _refresh
    self.__send_message(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/cursor.py", line 1039, in __send_message
    response = client._run_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1425, in _run_operation
    return self._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1534, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1501, in _retry_internal
    ).run()
      ^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2347, in run
    return self._read() if self._is_read else self._write()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2477, in _read
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2433, in _get_server
    return self._client._select_server(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1316, in _select_server
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/topology.py", line 369, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/topology.py", line 347, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/topology.py", line 254, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/topology.py", line 304, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66318f193acad48e9783b1bc, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-05-01T00:39:19.477+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=batch_analysis_dag, task_id=test_query, execution_date=20240501T003847, start_date=20240501T003848, end_date=20240501T003919
[2024-05-01T00:39:19.487+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task test_query (mongo:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66318f193acad48e9783b1bc, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>; 574)
[2024-05-01T00:39:19.500+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T00:39:19.512+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T00:39:19.513+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
